apiVersion: v2
appVersion: 3.4.13
description: CloudCasa backup service for Kubernetes and cloud native applications
home: https://cloudcasa.io
icon: https://raw.githubusercontent.com/catalogicsoftware/cloudcasa-helmchart/gh-pages/logo.png
keywords:
- Backup
- Catalogic
- CloudCasa
- Restore
- Copy
- Scan
kubeVersion: '>=1.17.0-0'
maintainers:
- email: support@cloudcasa.io
  name: catalogicsoftware
name: cloudcasa
version: 3.4.12
