## Please, note that this will override the parameters, including dependencies, configured to use the global value

## Cloudcasa AMDS Cluster ID. To be provided by the user.
cluster_id: ""

global:
  azure:
    identity:
      clientId: "DONOTMODIFY" # Azure populates this value at deployment time
    marketplace:
      planId: "DONOTMODIFY" # Azure populates this value at deployment time
    extension:
      resourceId: "DONOTMODIFY" # application's Azure Resource ID, Azure populates this value at deployment time
    images:
      kagent:
        digest: sha256:17dd8f1d1393d8042664090b28cd73765dc69cdad0c0bdbe4147ff5b442e1f2e
        image: kagent
        registry: catalogicsoftware.azurecr.io/marketplaceimages
