## Please, note that this will override the parameters, including dependencies, configured to use the global value

## Cloudcasa AMDS Cluster ID. To be provided by the user.
cluster_id: ""

global:
  azure:
    identity:
      clientId: "DONOTMODIFY" # Azure populates this value at deployment time
    marketplace:
      planId: "DONOTMODIFY" # Azure populates this value at deployment time
    extension:
      resourceId: "DONOTMODIFY" # application's Azure Resource ID, Azure populates this value at deployment time
    images:
      kagent:
        digest: sha256:36282c1179b6dbe0bc99bbd42fa206faf629923164407c1e30c12cf63310a336
        image: kagent
        registry: catalogicsoftware.azurecr.io/marketplaceimages
