---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudcasa-kubeagent-manager
  namespace: cloudcasa-io
  labels:
    component: cloudcasa-kubeagent-manager
    billing: {{ .Values.global.azure.billingIdentifier }}
spec:
  selector:
    matchLabels:
      app: cloudcasa-kubeagent-manager
  strategy: {}
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudcasa-kubeagent-manager
    spec:
      containers:
      - image: "{{ .Values.global.azure.images.kagent.registry }}/{{ .Values.global.azure.images.kagent.image }}@{{ .Values.global.azure.images.kagent.digest }}"
        args: ["/usr/local/bin/kubeagentmanager", "--server_addr", "agent.cloudcasa.io:443", "--tls", "true"]
        name: kubeagentmanager
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /scratch
          name: scratch
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: AMDS_CLUSTER_ID
          value: {{ .Values.cluster_id }}
        - name: KUBEMOVER_IMAGE
          value: "{{ .Values.global.azure.images.kagent.registry }}/{{ .Values.global.azure.images.kagent.image }}@{{ .Values.global.azure.images.kagent.digest }}"
        - name: DEPLOYMENT_PLATFORM
          value: "helm"
      restartPolicy: Always
      serviceAccountName: cloudcasa-io
      volumes:
      - emptyDir: {}
        name: scratch
---
