---
{{- if not (lookup "v1" "Namespace" "cloudcasa-io" "cloudcasa-io") }}
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  creationTimestamp: null
  labels:
    component: kubeagent-backup-helper
  name: cloudcasa-io
spec: {}
{{- end }}
---

